services:
  playwright:
    stdin_open: true
    tty: true
    env_file: .env
    build:
      context: "../"
      dockerfile: "./e2e/Dockerfile"
      target: "playwright"
    volumes:
      - "./../__snapshots__:/e2e/__snapshots__"
      - "./../packages/foundations/build:/e2e/packages/foundations/build"
      - "./../packages/components/build:/e2e/packages/components/build"
      - "./../build-showcases:/e2e/build-showcases"
      - "./../showcases:/e2e/showcases"
      - "./../output/react/playwright:/e2e/output/react/playwright"
      - "./../output/react/src:/e2e/output/react/src"
      - "./../output/vue/vue3/src:/e2e/output/vue/vue3/src"
      - type: bind
        source: ./package.json
        target: /e2e/package.json
      - type: bind
        source: ./../output/react/playwright.config.ts
        target: /e2e/output/react/playwright.config.ts
      - type: bind
        source: ./../output/vue/vue3/playwright.config.ts
        target: /e2e/output/vue/vue3/playwright.config.ts
