name: Init Workflow

on:
  workflow_call:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ Checkout repo
        uses: actions/checkout@v3

      - name: ðŸ”„ Init Cache Default
        id: "npm-cache"
        uses: ./.github/actions/npm-cache

      - name: ðŸŽ„ðŸ¥Š Log cache-hit
        run: echo $CACHE_HIT
        shell: bash
        env:
          CACHE_HIT: ${{steps.npm-cache.outputs.cache-hit}}

      - name: ðŸ“¥ Download deps default-npm-cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: bahmutov/npm-install@v1

      - name: ðŸ’€ Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
