---
name: Build outputs

on:
  workflow_call:

jobs:
  build-showcases:
    name: Build outputs
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Checkout repo
        uses: actions/checkout@v3

      - name: ðŸ”„ Init Cache
        uses: ./.github/actions/npm-cache

      - name: â¬‡ Download Packages
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-packages
          path: packages

      - name: ðŸ“¥ Install output dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm i

      - name: ðŸ”¨ Build outputs
        run: npm run build-outputs

      - name: â¬† Upload outputs
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: db-ui-outputs
          path: build-outputs

      - name: ðŸ’€ Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
