name: ğŸ­ Merge Playwright Reports

on:
  workflow_call:

permissions:
  actions: write
  contents: write

jobs:
  merge-playwright-reports:
    name: ğŸ­ Merge Playwright Reports
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ”„ Init Cache
        uses: ./.github/actions/npm-cache

      - name: â¬ Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-blob-reports
          path: all-blob-reports

      - name: ğŸ”€ Merge into HTML Report
        shell: bash
        run: |
          npx playwright merge-reports --reporter html ./all-blob-reports
          npx playwright merge-reports --reporter github ./all-blob-reports

      - name: ğŸ†™ Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
