---
name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  scan-secrets:
    if: github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui'
    uses: ./.github/workflows/00-scan-secrets.yml

  #  install-cypress:
  #    uses: ./.github/workflows/00-install-cypress.yml

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]

  build-packages:
    uses: ./.github/workflows/01-build-packages.yml
    needs: [init]

  build-showcases:
    uses: ./.github/workflows/01-build-showcases.yml
    needs: [build-packages]

  #  cypress:
  #    uses: ./.github/workflows/02-cypress.yml
  #    needs: [install-cypress]

  checks-done:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸŽ‰ Checks done
        run: echo "ðŸŽ‰ All tests were successful."
    #    needs: [cypress]
    needs: [build-showcases]

  deploy:
    uses: ./.github/workflows/03-deploy-gh-pages.yml
    if: ${{ github.actor != 'dependabot[bot]' && (github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui') }}
    needs: [checks-done]
    with:
      release: false
      preRelease: false
