---
name: Test and publish to package registries after new GitHub release

on:
  release:
    types: [published]

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  get-publish-version:
    uses: ./.github/workflows/01-get-publish-version.yml
    needs: [init]

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]

  build-packages:
    uses: ./.github/workflows/01-build-packages.yml
    needs: [init]

  build-outputs:
    uses: ./.github/workflows/01-build-outputs.yml
    needs: [build-packages]

  build-showcases:
    uses: ./.github/workflows/01-build-showcases.yml
    needs: [build-packages, get-publish-version]
    with:
      release: ${{ needs.get-publish-version.outputs.release }}
      preRelease: ${{ needs.get-publish-version.outputs.preRelease }}

  test-components:
    uses: ./.github/workflows/02-e2e.yml
    needs: [build-packages]

  build-power-apps:
    uses: ./.github/workflows/01-build-power-apps.yml
    needs: [get-publish-version, build-packages]
    secrets: inherit
    with:
      version: ${{ needs.get-publish-version.outputs.version }}

  test-showcases:
    uses: ./.github/workflows/02-e2e-showcases.yml
    needs: [build-showcases]

  merge-reports:
    if: ${{ always() }}
    uses: ./.github/workflows/03-e2e-merge-reports.yml
    needs: [test-components, test-showcases]

  checks-done:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸŽ‰ Checks done
        run: echo "ðŸŽ‰ All builds were successful."
    needs:
      [
        test-components,
        build-outputs,
        build-showcases,
        test-showcases,
        build-power-apps
      ]

  deploy:
    uses: ./.github/workflows/03-deploy-gh-pages.yml
    needs: [checks-done, get-publish-version]
    with:
      release: ${{ needs.get-publish-version.outputs.release }}
      preRelease: ${{ needs.get-publish-version.outputs.preRelease }}

  publishpackages:
    uses: ./.github/workflows/03-publish-packages.yml
    needs: [get-publish-version, checks-done, build-outputs]
    secrets: inherit
    with:
      release: ${{ needs.get-publish-version.outputs.release }}
      preRelease: ${{ needs.get-publish-version.outputs.preRelease }}
      version: ${{ needs.get-publish-version.outputs.version }}
